/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AdoptionInterface extends ethers.utils.Interface {
  functions: {
    "deleteMe()": FunctionFragment;
    "getPetOwner(string)": FunctionFragment;
    "sendPetToBeAdopted(string)": FunctionFragment;
    "setDeleteMe(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "deleteMe", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPetOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "sendPetToBeAdopted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeleteMe",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deleteMe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPetOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPetToBeAdopted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeleteMe",
    data: BytesLike
  ): Result;

  events: {};
}

export class Adoption extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AdoptionInterface;

  functions: {
    deleteMe(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPetOwner(
      petName: string,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    sendPetToBeAdopted(
      petName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDeleteMe(
      newDeleteMe: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deleteMe(overrides?: CallOverrides): Promise<BigNumber>;

  getPetOwner(petName: string, overrides?: CallOverrides): Promise<string>;

  sendPetToBeAdopted(
    petName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDeleteMe(
    newDeleteMe: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deleteMe(overrides?: CallOverrides): Promise<BigNumber>;

    getPetOwner(petName: string, overrides?: CallOverrides): Promise<string>;

    sendPetToBeAdopted(
      petName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDeleteMe(
      newDeleteMe: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    deleteMe(overrides?: CallOverrides): Promise<BigNumber>;

    getPetOwner(petName: string, overrides?: CallOverrides): Promise<BigNumber>;

    sendPetToBeAdopted(
      petName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDeleteMe(
      newDeleteMe: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deleteMe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPetOwner(
      petName: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sendPetToBeAdopted(
      petName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDeleteMe(
      newDeleteMe: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
