/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Adoption } from "./Adoption";

export { Adoption__factory } from "./factories/Adoption__factory";
